SUBROUTINE PKMB.READ.SL

$INSERT I_COMMON
$INSERT I_EQUATE

GOSUB INIT
GOSUB OPEN.FILE
GOSUB PROCESS


INIT:

	Y.EOF = 0
	Y.LINE = ''
	Y.DIR  = "&SAVEDLISTS&"
	Y.FILE = ''
	Y.APP = ''
	Y.ID = ''
	Y.FILE.APP = ''
	Y.FILE.FOUND = ''
	Y.FILE.NOTFOUND = ''
	Y.ARR.FOUND = ''
	Y.ARR.NOTFOUND = ''
	
	RETURN
	
OPEN.FILE:


	CRT "Input the file name"

	INPUT Y.FILE
	
	IF Y.FILE EQ '' THEN
           CRT "Input the file name"
           INPUT Y.FILE
    END
	OPENSEQ Y.DIR,Y.FILE TO Y.LOG.FILE
		 
	ELSE
		
		CRT "FILE DOESNOT EXIST"
		       
	END
		
		
RETURN

PROCESS:

    LOOP
	READSEQ Y.REC FROM Y.LOG.FILE ELSE EXIT
	Y.FILE.ARRAY : = Y.REC:@FM:
	REPEAT
	
	Y.CNT = DCOUNT(Y.FILE.ARRAY,@FM)
	
	FOR I = 1 TO Y.CNT
                Y.ARR.REC = Y.FILE.ARRAY<I>
		Y.APP = FIELD(Y.ARR.REC,">",1)
		Y.ID  = FIELD(Y.ARR.REC,">",2)
		
		Y.FILE.APP = "F.":Y.APP
        Y.POINTER = ''
		IF Y.APP NE '' AND Y.FILE.APP NE '' AND Y.ID NE '' THEN

			CALL OPF (Y.FILE.APP, Y.POINTER)
			
			CALL F.READ(Y.FILE.APP,Y.ID,R.REC,Y.POINTER,Y.ERR)
			
			IF Y.ERR EQ '' THEN
			
				Y.ARR.FOUND := Y.FILE.ARRAY<I>:@FM:
			
			END 
			
			IF Y.ERR NE '' THEN
			
				Y.ARR.NOTFOUND:= Y.FILE.ARRAY<I>:@FM:
			
			END 
			
		END
    NEXT I

		GOSUB WRITE.FILE1
		GOSUB WRITE.FILE2
	

RETURN

WRITE.FILE1:
    Y.FILE.FOUND = Y.FILE:'.FOUND'
    SEQ.FILE.NAME = Y.DIR
    RECORD.NAME = Y.FILE.FOUND

    SEQ.FILE.POINTER = ''
    

    OPENSEQ SEQ.FILE.NAME,RECORD.NAME TO SEQ.FILE.POINTER ELSE
        CREATE SEQ.FILE.POINTER ELSE
            STOP
        END
    END
    Y.NO.MSG = DCOUNT(Y.ARR.FOUND,@FM)
    Y.ST.PT = '1'
    LOOP
        WHILE Y.ST.PT LE Y.NO.MSG DO
        WRITESEQ Y.ARR.FOUND<Y.ST.PT> TO SEQ.FILE.POINTER THEN
        END
         Y.ST.PT++
     REPEAT
    CLOSESEQ SEQ.FILE.POINTER


RETURN

WRITE.FILE2:

    Y.FILE.NOTFOUND = Y.FILE:'.NOT.FOUND'
    SEQ.FILE.NAME = Y.DIR
    RECORD.NAME = Y.FILE.NOTFOUND

    SEQ.FILE.POINTER = ''

    OPENSEQ SEQ.FILE.NAME,RECORD.NAME TO SEQ.FILE.POINTER ELSE
        CREATE SEQ.FILE.POINTER ELSE
            STOP
        END
    END

    Y.NO.MSG = DCOUNT(Y.ARR.NOTFOUND,@FM)
    Y.ST.PT = '1'
    LOOP
        WHILE Y.ST.PT LE Y.NO.MSG DO
        WRITESEQ Y.ARR.NOTFOUND<Y.ST.PT> TO SEQ.FILE.POINTER THEN
        END
         Y.ST.PT++
     REPEAT
    CLOSESEQ SEQ.FILE.POINTER



RETURN

END
	